name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      # Install dependencies
      - name: Install dependencies
        run: npm i

      - name: Publish cli
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SVGD_NPM_TOKEN }}
