name: Update MUI Icons

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout MUI icons
        uses: actions/checkout@v4
        with:
          repository: mui/material-ui
          token: ${{ secrets.GITHUB_TOKEN }}
          path: mui-material-ui
          fetch-depth: 1
          persist-credentials: false

          sparse-checkout: |
            packages/mui-icons-material/material-icons
            packages/mui-icons-material/package.json

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Generate icons
        run: npx -y @svgd/cli --input mui-material-ui/packages/mui-icons-material/material-icons --output ./icons/paths.js --format material --html ./html/index.html --dts

      - name: Sync version from MUI package
        run: |
          node - <<'EOF'
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          const muiPkg = JSON.parse(fs.readFileSync('mui-material-ui/packages/mui-icons-material/package.json', 'utf8'));
          pkgVersion = pkg.version.split(".");
          muiPkgVersion = muiPkg.version.split(".");
          pkg.version = (muiPkgVersion[0] * 10000 + muiPkgVersion[1] * 1 > pkgVersion[0] * 10000 + pkgVersion[1] * 1) ? muiPkg.version : [muiPkgVersion[0], muiPkgVersion[1], muiPkgVersion[2] * 1 >= pkgVersion[2] * 1 ? muiPkgVersion[2] : pkgVersion[2] * 1 + 1].join(".");
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
          EOF

      - name: Commit icons
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add ./icons
          git add ./html
          git add package.json
          git commit -m "chore: update generated icons" || echo "No changes to commit"
          git push
